### ISSUE TITLE
Not an issue, discussion

### ISSUE THREAD

**Issue by Matthew-Bradley** [DrewTChrist/atwinc1500-rs#14]
Just wanted to say hi! I've been following along closely for a little while, as I've got a bunch of these modules and would like to make use of them under rust some day. Really excited to see each bit of progress!

(I have a bunch of 8KB ram AVRs that are low-speed-grade, and it looks easier to run them at 8MHz under rust than arduino. I also in general want to get into programming AVRs in rust)

I dunno if an issue is the best place to discuss things though, does github have general discussion forum?

**Comment by DrewTChrist** [comment]
Hey! I'm happy to hear about your interest. Github appears to have added discussion board functionality. I've enabled discussions for the repo and started one [here](https://github.com/DrewTChrist/atwinc1500-rs/discussions/15). (The discussions tab should be visible on this repo now) 

Feel free to share any thoughts or questions you have there. It would be great to get some input from someone that isn't myself.
